version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: reason
      WORDPRESS_DB_PASSWORD: digital
      WORDPRESS_DB_NAME: wordpresstask
    volumes:
      - wordpress:/var/www/html/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpresstask
      MYSQL_USER: reason
      MYSQL_PASSWORD: digital
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  wordpress:
  db:
